import {
  BadgeIndianRupee,
  Boxes,
  Building2,
  ChartNoAxesCombined,
  CircuitBoard,
  Gem,
  HardHat,
  Leaf,
  Megaphone,
  MonitorSmartphone,
  PackageCheck,
  Palette,
  Plane,
  Printer,
  Shirt,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Store,
  Truck,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

export const companies = [
  {
    id: "kavya-textiles",
    name: "Kavya Textiles",
    legalName: "Kavya Textiles Private Limited",
    initials: "KT",
    industry: "Textile",
    gstin: "24ABCDE1234F1Z5",
    city: "Ahmedabad",
    state: "Gujarat",
    currency: "INR",
    financialYear: "FY 2026-27",
    role: "Owner",
    status: "Active",
    salesThisMonth: 942000,
    receivables: 174200,
    stockValue: 618000,
    aiCreditsUsed: 784,
    aiCreditLimit: 1200,
  },
  {
    id: "prime-mobile",
    name: "Prime Mobile Hub",
    legalName: "Prime Mobile Hub LLP",
    initials: "PM",
    industry: "Mobile Shop",
    gstin: "24BBBCP8821M1Z9",
    city: "Rajkot",
    state: "Gujarat",
    currency: "INR",
    financialYear: "FY 2026-27",
    role: "Admin",
    status: "Active",
    salesThisMonth: 728000,
    receivables: 74100,
    stockValue: 412000,
    aiCreditsUsed: 426,
    aiCreditLimit: 900,
  },
  {
    id: "nisha-fashion",
    name: "Nisha Fashion Studio",
    legalName: "Nisha Fashion Studio",
    initials: "NF",
    industry: "Garment",
    gstin: "24AAAFN5454R1Z1",
    city: "Bhavnagar",
    state: "Gujarat",
    currency: "INR",
    financialYear: "FY 2026-27",
    role: "Accountant",
    status: "Active",
    salesThisMonth: 386000,
    receivables: 18600,
    stockValue: 284000,
    aiCreditsUsed: 198,
    aiCreditLimit: 600,
  },
] as const;

export const aiPlans = [
  {
    id: "free",
    name: "Free",
    price: "Rs. 0",
    billingPeriod: "year",
    companyLimit: 1,
    userLimit: 1,
    aiCreditLimit: 100,
    ewayBillLimit: 10,
    trialDays: 0,
    recommended: false,
    description: "Permanent free web workspace for one owner exploring billing and AI basics.",
    featureHighlights: ["1 company", "1 owner user", "100 AI credits/month", "Starter reports"],
    featureDetails: [
      "Create GST invoices with customer, item, tax, and due-date fields",
      "Maintain basic customer and vendor ledgers for follow-up",
      "Track simple inventory items with stock quantity and value",
      "View starter reports for sales, stock, receivables, and expenses",
      "Use 100 common AI credits per month for simple summaries and invoice help",
      "Keep one owner login for a single company workspace",
    ],
  },
  {
    id: "basic",
    name: "Basic",
    price: "Rs. 1,499",
    billingPeriod: "year / company",
    companyLimit: 1,
    userLimit: 2,
    aiCreditLimit: 300,
    ewayBillLimit: 50,
    trialDays: 14,
    recommended: false,
    description: "Affordable web plan for small shops starting with GST billing and inventory.",
    featureHighlights: ["1 company", "2 users", "300 AI credits/month", "50 e-way bills"],
    featureDetails: [
      "Create GST invoices, purchases, expenses, and payment records",
      "Track inventory with SKU, stock quantity, reorder level, and item value",
      "Manage customer and vendor balances with contact details and GSTIN",
      "Use reports for sales, purchases, expenses, stock, receivables, and payables",
      "Generate up to 50 e-way bill drafts for dispatch workflows",
      "Use 300 common AI credits per month for summaries, reminders, and stock checks",
    ],
  },
  {
    id: "professional",
    name: "Professional",
    price: "Rs. 2,999",
    billingPeriod: "year / company",
    companyLimit: 3,
    userLimit: 5,
    aiCreditLimit: 800,
    ewayBillLimit: 150,
    trialDays: 14,
    recommended: true,
    description: "Best value web plan for most MSMEs managing up to 3 companies, billing, stock, accounting, and reports.",
    featureHighlights: ["Up to 3 companies", "5 users", "800 AI credits/month", "150 e-way bills"],
    featureDetails: [
      "Manage up to 3 company workspaces under one owner account",
      "Create invoices, purchases, expenses, payments, and credit/debit notes",
      "Track stock with SKU, serial number, reorder level, batch, expiry, and valuation",
      "Use accounting workflows for ledgers, payables, receivables, banking, and GST summary",
      "Generate e-way bill drafts with vehicle, transporter, GSTIN, distance, and dispatch details",
      "Run detailed reports: profit loss, balance sheet, sale detail, purchase detail, stock, GSTR, receivables, and payables",
      "Invite up to 5 users per company with role-based access for owner, accountant, sales, inventory, and reporting workflows",
      "Use 800 common AI credits per month for invoice drafts, report summaries, stock risk checks, and collection reminders",
    ],
  },
  {
    id: "business",
    name: "Business",
    price: "Custom",
    billingPeriod: "custom",
    companyLimit: 5,
    userLimit: 25,
    aiCreditLimit: 5000,
    ewayBillLimit: 1000,
    trialDays: 14,
    recommended: false,
    description: "For larger teams needing heavier AI workflows, approvals, custom limits, and multiple companies.",
    featureHighlights: ["5+ companies", "25 users/company", "5,000 AI credits/month", "Priority support"],
    featureDetails: [
      "Run 5 or more company workspaces with custom onboarding support",
      "Invite up to 25 users per company with role-based access and audit controls",
      "Use higher-capacity billing, inventory, accounting, payroll, and reporting workflows",
      "Generate up to 1,000 e-way bill drafts with larger dispatch capacity",
      "Use 5,000 common AI credits per month for heavier automation and reporting",
      "Get priority support for setup, migration planning, approvals, exports, and team rollout",
    ],
  },
] as const;

export const planAddOns = [
  { id: "extra-user", name: "Extra user", price: "Rs. 299/user/year", description: "Add one more active or invited team member." },
  { id: "ai-top-up", name: "AI top-up", price: "Rs. 299", description: "Add 500 credits to the common company AI wallet." },
  { id: "eway-pack", name: "E-way bill pack", price: "Rs. 399", description: "Add 250 extra e-way bill generations." },
  { id: "extra-company", name: "Extra company", price: "Rs. 999/company/year", description: "Add another legal company workspace." },
] as const;

export const industries = [
  ["Textile", "Rolls, meters, dye lots", Shirt],
  ["Garment", "Sizes, colors, collections", Shirt],
  ["Electronics", "Serials and warranty", Zap],
  ["Agriculture", "Seasonal stock planning", Leaf],
  ["Mobile Shop", "IMEI and repair billing", Smartphone],
  ["E-commerce", "Orders and returns", ShoppingCart],
  ["Stationary", "Fast low-value SKUs", Store],
  ["Auto Parts", "Part numbers and fitment", Wrench],
  ["Computer & CCTV", "Hardware and AMC", MonitorSmartphone],
  ["Chemical", "Batch and expiry fields", ShieldCheck],
  ["IT Company", "Retainers and projects", CircuitBoard],
  ["Marketing Agency", "Campaign profitability", Megaphone],
  ["Packaging", "Dimensions and bulk jobs", PackageCheck],
  ["Ceramic", "Boxes and area tracking", Boxes],
  ["Furniture", "Custom orders and delivery", Sofa],
  ["Building Material", "Weight and transport", HardHat],
  ["Hardware & Plywood", "Mixed retail and cutting", Wrench],
  ["Cosmetic", "Expiry and MRP control", Sparkles],
  ["Fire Safety", "Refill and compliance", ShieldCheck],
  ["Diamond & Jewelry", "Purity and making charge", Gem],
  ["Scrap", "Weight slips and rates", Truck],
  ["Printing & Designing", "Job cards and approvals", Printer],
  ["Rental Services", "Bookings and deposits", BadgeIndianRupee],
  ["Travel Agency", "Bookings and commission", Plane],
] as const;

export const customers = [
  { id: "c1", name: "Kavya Textiles", type: "Textile", gstin: "24ABCDE1234F1Z5", contact: "Rohan Shah", city: "Ahmedabad", balance: 82400, status: "Overdue", phone: "+91 98765 43210" },
  { id: "c2", name: "Mehta Traders", type: "Retail", gstin: "24AABCM2345K1Z8", contact: "Jignesh Mehta", city: "Surat", balance: 46800, status: "Sent", phone: "+91 98250 12888" },
  { id: "c3", name: "Shree Stores", type: "Stationary", gstin: "24AAWFS9090D1ZA", contact: "Asha Patel", city: "Vadodara", balance: 0, status: "Paid", phone: "+91 99099 11990" },
  { id: "c4", name: "Prime Mobile", type: "Mobile Shop", gstin: "24BBBCP8821M1Z9", contact: "Nilesh Vora", city: "Rajkot", balance: 74100, status: "Draft", phone: "+91 90165 22210" },
  { id: "c5", name: "Nisha Fashion", type: "Garment", gstin: "24AAAFN5454R1Z1", contact: "Nisha Jain", city: "Bhavnagar", balance: 18600, status: "Sent", phone: "+91 98790 45010" },
];

export const invoices = [
  {
    id: "INV-1048",
    customer: "Kavya Textiles",
    status: "Overdue",
    issueDate: "22 Apr 2026",
    dueDate: "29 Apr 2026",
    amount: 82400,
    taxable: 69831,
    gst: 12569,
    payment: "Partial",
    paid: 50000,
    owner: "Priya Patel",
    channel: "Wholesale textile dispatch",
    ewayStatus: "Generated",
    nextAction: "Call Rohan Shah before 4 PM",
  },
  {
    id: "INV-1049",
    customer: "Mehta Traders",
    status: "Sent",
    issueDate: "25 Apr 2026",
    dueDate: "02 May 2026",
    amount: 46800,
    taxable: 39661,
    gst: 7139,
    payment: "Awaiting",
    paid: 0,
    owner: "Rohan Shah",
    channel: "Retail counter supply",
    ewayStatus: "Draft",
    nextAction: "Send payment reminder on WhatsApp",
  },
  {
    id: "INV-1050",
    customer: "Shree Stores",
    status: "Paid",
    issueDate: "20 Apr 2026",
    dueDate: "26 Apr 2026",
    amount: 31950,
    taxable: 27076,
    gst: 4874,
    payment: "Received",
    paid: 31950,
    owner: "Asha Mehta",
    channel: "Stationary monthly refill",
    ewayStatus: "Not required",
    nextAction: "Close ledger and email receipt",
  },
  {
    id: "INV-1051",
    customer: "Prime Mobile",
    status: "Draft",
    issueDate: "29 Apr 2026",
    dueDate: "03 May 2026",
    amount: 74100,
    taxable: 62797,
    gst: 11303,
    payment: "Draft",
    paid: 0,
    owner: "Neel Savaliya",
    channel: "Mobile accessories bulk sale",
    ewayStatus: "Ready",
    nextAction: "Confirm IMEI/serial list before sending",
  },
  {
    id: "INV-1052",
    customer: "Nisha Fashion",
    status: "Sent",
    issueDate: "30 Apr 2026",
    dueDate: "06 May 2026",
    amount: 18600,
    taxable: 16607,
    gst: 1993,
    payment: "Awaiting",
    paid: 0,
    owner: "Priya Patel",
    channel: "Garment sample order",
    ewayStatus: "Not required",
    nextAction: "Check delivery confirmation",
  },
];

export const inventory = [
  { sku: "A-12", serialNumber: "TXT-A12-2026-0008", name: "Cotton roll A-12", category: "Textile", unit: "Roll", stock: 8, reorder: 20, purchase: 1450, sale: 1850, status: "Low stock" },
  { sku: "D-44", serialNumber: "GRM-D44-2026-0064", name: "Denim bundle blue", category: "Garment", unit: "Bundle", stock: 64, reorder: 30, purchase: 2050, sale: 2450, status: "Healthy" },
  { sku: "C-18", serialNumber: "ELC-C18-USB-0140", name: "USB cable pack", category: "Electronics", unit: "Pack", stock: 140, reorder: 80, purchase: 220, sale: 300, status: "Slow moving" },
  { sku: "P-09", serialNumber: "STN-P09-INK-0018", name: "Printer ink batch", category: "Stationary", unit: "Box", stock: 18, reorder: 24, purchase: 900, sale: 1200, status: "Reorder" },
  { sku: "M-05", serialNumber: "IMEI-BULK-M05-0210", name: "Mobile tempered glass", category: "Mobile Shop", unit: "Piece", stock: 210, reorder: 100, purchase: 45, sale: 120, status: "Healthy" },
  { sku: "F-5K", serialNumber: "FIRE-5KG-2026-0016", name: "Fire extinguisher 5kg", category: "Fire Safety", unit: "Piece", stock: 16, reorder: 12, purchase: 2100, sale: 3100, status: "Healthy" },
];

export const users = [
  { name: "Neel Savaliya", email: "owner@koshpilot.app", role: "Owner", status: "Active", active: "Today", scope: "All access" },
  { name: "Priya Patel", email: "priya@koshpilot.app", role: "Accountant", status: "Active", active: "Today", scope: "Billing, reports" },
  { name: "Rohan Shah", email: "rohan@koshpilot.app", role: "Sales", status: "Invited", active: "Pending", scope: "Customers, invoices" },
  { name: "Asha Mehta", email: "asha@koshpilot.app", role: "Inventory Manager", status: "Active", active: "Yesterday", scope: "Stock only" },
];

export const reports = [
  { title: "Sales vs expenses", value: "12% sales growth", icon: ChartNoAxesCombined },
  { title: "Receivables aging", value: "INR 1.74L at risk", icon: Users },
  { title: "Stock value trend", value: "INR 6.18L inventory", icon: Boxes },
  { title: "GST summary", value: "INR 84.2k payable", icon: Building2 },
];

export const expenses = [
  { id: "EXP-2101", vendor: "Surat Transport Co.", category: "Transport", date: "02 May 2026", amount: 12600, status: "Approved", tax: "18%" },
  { id: "EXP-2102", vendor: "Apex Packaging", category: "Packaging", date: "01 May 2026", amount: 8400, status: "Pending", tax: "12%" },
  { id: "EXP-2103", vendor: "Office Hub", category: "Office supplies", date: "29 Apr 2026", amount: 3200, status: "Paid", tax: "18%" },
  { id: "EXP-2104", vendor: "Cloud Tools India", category: "Software", date: "28 Apr 2026", amount: 5500, status: "Paid", tax: "18%" },
];

export const purchases = [
  { id: "PO-1187", supplier: "Rang Fabrics", status: "Received", date: "30 Apr 2026", amount: 145000, payable: 35000 },
  { id: "PO-1188", supplier: "Apex Packaging", status: "Ordered", date: "02 May 2026", amount: 42000, payable: 42000 },
  { id: "PO-1189", supplier: "Tech Cable Mart", status: "Partial", date: "03 May 2026", amount: 58000, payable: 18000 },
];

export const payments = [
  { id: "PAY-3021", party: "Kavya Textiles", type: "Received", mode: "UPI", date: "04 May 2026", amount: 50000, status: "Matched" },
  { id: "PAY-3022", party: "Rang Fabrics", type: "Paid", mode: "Bank", date: "03 May 2026", amount: 30000, status: "Matched" },
  { id: "PAY-3023", party: "Mehta Traders", type: "Received", mode: "Cash", date: "02 May 2026", amount: 12000, status: "Unmatched" },
];

export const ledgerEntries = [
  { date: "04 May 2026", account: "Accounts Receivable", debit: 82400, credit: 0, ref: "INV-1048" },
  { date: "04 May 2026", account: "Sales Revenue", debit: 0, credit: 69831, ref: "INV-1048" },
  { date: "04 May 2026", account: "Output GST", debit: 0, credit: 12569, ref: "INV-1048" },
  { date: "03 May 2026", account: "Transport Expense", debit: 12600, credit: 0, ref: "EXP-2101" },
];

export const bankTransactions = [
  { id: "BNK-9021", date: "04 May 2026", narration: "UPI Kavya Textiles", amount: 50000, type: "Credit", status: "Reconciled" },
  { id: "BNK-9022", date: "03 May 2026", narration: "NEFT Rang Fabrics", amount: 30000, type: "Debit", status: "Reconciled" },
  { id: "BNK-9023", date: "02 May 2026", narration: "Cash deposit", amount: 12000, type: "Credit", status: "Needs review" },
];

export const gstSummary = [
  { label: "Output GST", amount: 142300, status: "Collected" },
  { label: "Input GST", amount: 58100, status: "Credit" },
  { label: "Net payable", amount: 84200, status: "Due" },
  { label: "GSTR-1 readiness", amount: 96, status: "Ready %" },
];

export const employees = [
  { id: "EMP-001", name: "Priya Patel", role: "Accountant", department: "Finance", status: "Active", salary: 52000, attendance: "24/26", joining: "12 Jan 2025" },
  { id: "EMP-002", name: "Rohan Shah", role: "Sales Executive", department: "Sales", status: "Active", salary: 42000, attendance: "23/26", joining: "04 Mar 2025" },
  { id: "EMP-003", name: "Asha Mehta", role: "Inventory Manager", department: "Operations", status: "Active", salary: 46000, attendance: "25/26", joining: "18 Jun 2024" },
  { id: "EMP-004", name: "Nilesh Vora", role: "Support Agent", department: "Support", status: "On leave", salary: 36000, attendance: "18/26", joining: "22 Aug 2025" },
];

export const payrollRuns = [
  { id: "PAYRUN-0526", period: "May 2026", employees: 4, gross: 176000, deductions: 18400, net: 157600, status: "Draft" },
  { id: "PAYRUN-0426", period: "Apr 2026", employees: 4, gross: 176000, deductions: 17600, net: 158400, status: "Paid" },
  { id: "PAYRUN-0326", period: "Mar 2026", employees: 3, gross: 140000, deductions: 13200, net: 126800, status: "Paid" },
];

export const ewayBills = [
  { id: "EWB-2426-0018", invoice: "INV-1048", customer: "Kavya Textiles", transporter: "Surat Transport Co.", vehicle: "GJ05AB1234", distance: 265, validUntil: "08 May 2026", status: "Generated", amount: 82400 },
  { id: "EWB-2426-0019", invoice: "INV-1049", customer: "Mehta Traders", transporter: "Swift Cargo", vehicle: "GJ01CT8890", distance: 92, validUntil: "06 May 2026", status: "Draft", amount: 46800 },
  { id: "EWB-2426-0020", invoice: "INV-1051", customer: "Prime Mobile", transporter: "Rajkot Logistics", vehicle: "GJ03BX4401", distance: 218, validUntil: "09 May 2026", status: "Ready", amount: 74100 },
];

export const aiCreditSummary = {
  plan: "Professional",
  monthlyLimit: 800,
  used: 784,
  resetDate: "01 Jun 2026",
  warningAt: 640,
};

export const aiUsageLogs = [
  { id: "AI-9081", page: "Invoices", action: "Generated invoice draft for Kavya Textiles", credits: 18, user: "Priya Patel", time: "Today, 10:42 AM", status: "Completed" },
  { id: "AI-9080", page: "E-way bills", action: "Validated GSTIN, distance, and vehicle number", credits: 12, user: "Neel Savaliya", time: "Today, 10:18 AM", status: "Completed" },
  { id: "AI-9079", page: "Reports", action: "Summarized sales, expenses, receivables, and stock", credits: 24, user: "Neel Savaliya", time: "Yesterday, 06:22 PM", status: "Completed" },
  { id: "AI-9078", page: "Inventory", action: "Flagged low-stock and reorder risks", credits: 10, user: "Asha Mehta", time: "Yesterday, 04:15 PM", status: "Completed" },
  { id: "AI-9077", page: "Customers", action: "Drafted payment reminder messages", credits: 14, user: "Rohan Shah", time: "02 May 2026", status: "Reviewed" },
];
